language: go

go:
  - 1.5

# mongodb is used for all testing
services: mongodb


# the entire framework is on revel so dependencies
install:
    - go get github.com/revel/revel
    - go get github.com/revel/cmd/revel

    - go get gopkg.in/mgo.v2/bson
    - go get gopkg.in/check.v1

    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

# the below is to add an artifical wait for mongodb 
# to start as per travis-ci doc http://docs.travis-ci.com/user/database-setup/
before_script:
    - sleep 15
    - mongo mydb_test --eval 'db.addUser("travis", "test");'

    - $HOME/gopath/bin/goveralls -service=travis-ci

